language: node_js

version: 1.0

node_js: "10"

cache:
  npm: false
  yarn: false

script:
  - yarn lint:js
  - yarn lint:style
  - yarn test
  - yarn build
  - yarn build:docs

deploy:
  - provider: npm
    edge: true
    email: "$NPM_EMAIL"
    api_key: "$NPM_TOKEN"
    skip_cleanup: true
    on:
      tags: true
      branch: master
  - provider: netlify
    site: cra-template-quickstart-redux.netlify.com
    auth: "$NETLIFY_TOKEN"
    dir: docz-dist
    prod: true
    cleanup: false
    edge: true
    on:
      branch: master

notifications:
  email: false
