language: node_js

version: 1.0

node_js: "10"

cache:
  directories:
    - node_modules

script:
  - yarn lint:js
  - yarn lint:style
  - yarn test
  - yarn build

deploy:
  - provider: npm
    edge: true
    email: "$NPM_EMAIL"
    api_key: "$NPM_TOKEN"
    skip_cleanup: true
    on:
      tags: true
      branch: master

notifications:
  email: false